[2023-08-07T04:47:27.806+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: perform_s3_tasks.load_files_into_bucket manual__2023-08-07T04:36:09.870769+00:00 [queued]>
[2023-08-07T04:47:27.827+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: perform_s3_tasks.load_files_into_bucket manual__2023-08-07T04:36:09.870769+00:00 [queued]>
[2023-08-07T04:47:27.828+0000] {taskinstance.py:1308} INFO - Starting attempt 7 of 11
[2023-08-07T04:47:27.858+0000] {taskinstance.py:1327} INFO - Executing <Task(LocalFilesystemToS3Operator): load_files_into_bucket> on 2023-08-07 04:36:09.870769+00:00
[2023-08-07T04:47:27.868+0000] {standard_task_runner.py:57} INFO - Started process 417 to run task
[2023-08-07T04:47:27.881+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'perform_s3_tasks', 'load_files_into_bucket', 'manual__2023-08-07T04:36:09.870769+00:00', '--job-id', '13', '--raw', '--subdir', 'DAGS_FOLDER/s3_dag.py', '--cfg-path', '/tmp/tmpgcr8kwkq']
[2023-08-07T04:47:27.885+0000] {standard_task_runner.py:85} INFO - Job 13: Subtask load_files_into_bucket
[2023-08-07T04:47:28.002+0000] {task_command.py:410} INFO - Running <TaskInstance: perform_s3_tasks.load_files_into_bucket manual__2023-08-07T04:36:09.870769+00:00 [running]> on host 95071573e7de
[2023-08-07T04:47:28.153+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='abhi' AIRFLOW_CTX_DAG_ID='perform_s3_tasks' AIRFLOW_CTX_TASK_ID='load_files_into_bucket' AIRFLOW_CTX_EXECUTION_DATE='2023-08-07T04:36:09.870769+00:00' AIRFLOW_CTX_TRY_NUMBER='7' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-08-07T04:36:09.870769+00:00'
[2023-08-07T04:47:28.155+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/amazon/aws/transfers/local_to_s3.py", line 98, in execute
    self.dest_bucket, self.dest_key, "dest_bucket", "dest_key"
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 225, in get_s3_bucket_key
    f"If `{bucket_param_name}` is provided, {key_param_name} should be a relative path "
TypeError: If `dest_bucket` is provided, dest_key should be a relative path from root level, rather than a full s3:// url
[2023-08-07T04:47:28.169+0000] {taskinstance.py:1350} INFO - Marking task as UP_FOR_RETRY. dag_id=perform_s3_tasks, task_id=load_files_into_bucket, execution_date=20230807T043609, start_date=20230807T044727, end_date=20230807T044728
[2023-08-07T04:47:28.188+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 13 for task load_files_into_bucket (If `dest_bucket` is provided, dest_key should be a relative path from root level, rather than a full s3:// url; 417)
[2023-08-07T04:47:28.218+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-08-07T04:47:28.278+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
