[2023-08-07T04:49:03.594+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: perform_s3_tasks.load_files_into_bucket manual__2023-08-07T04:48:59.150134+00:00 [queued]>
[2023-08-07T04:49:03.613+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: perform_s3_tasks.load_files_into_bucket manual__2023-08-07T04:48:59.150134+00:00 [queued]>
[2023-08-07T04:49:03.614+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 6
[2023-08-07T04:49:03.642+0000] {taskinstance.py:1327} INFO - Executing <Task(LocalFilesystemToS3Operator): load_files_into_bucket> on 2023-08-07 04:48:59.150134+00:00
[2023-08-07T04:49:03.649+0000] {standard_task_runner.py:57} INFO - Started process 449 to run task
[2023-08-07T04:49:03.655+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'perform_s3_tasks', 'load_files_into_bucket', 'manual__2023-08-07T04:48:59.150134+00:00', '--job-id', '15', '--raw', '--subdir', 'DAGS_FOLDER/s3_dag.py', '--cfg-path', '/tmp/tmp5gc_vj0k']
[2023-08-07T04:49:03.659+0000] {standard_task_runner.py:85} INFO - Job 15: Subtask load_files_into_bucket
[2023-08-07T04:49:03.765+0000] {task_command.py:410} INFO - Running <TaskInstance: perform_s3_tasks.load_files_into_bucket manual__2023-08-07T04:48:59.150134+00:00 [running]> on host 95071573e7de
[2023-08-07T04:49:03.912+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='abhi' AIRFLOW_CTX_DAG_ID='perform_s3_tasks' AIRFLOW_CTX_TASK_ID='load_files_into_bucket' AIRFLOW_CTX_EXECUTION_DATE='2023-08-07T04:48:59.150134+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-08-07T04:48:59.150134+00:00'
[2023-08-07T04:49:03.914+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/amazon/aws/transfers/local_to_s3.py", line 98, in execute
    self.dest_bucket, self.dest_key, "dest_bucket", "dest_key"
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 225, in get_s3_bucket_key
    f"If `{bucket_param_name}` is provided, {key_param_name} should be a relative path "
TypeError: If `dest_bucket` is provided, dest_key should be a relative path from root level, rather than a full s3:// url
[2023-08-07T04:49:03.931+0000] {taskinstance.py:1350} INFO - Marking task as UP_FOR_RETRY. dag_id=perform_s3_tasks, task_id=load_files_into_bucket, execution_date=20230807T044859, start_date=20230807T044903, end_date=20230807T044903
[2023-08-07T04:49:03.961+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 15 for task load_files_into_bucket (If `dest_bucket` is provided, dest_key should be a relative path from root level, rather than a full s3:// url; 449)
[2023-08-07T04:49:03.990+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-08-07T04:49:04.050+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
